<center><h1> <b>--> Array <--</b></h1></center>
<h1><center><b>Week-1 </b></center></h1>
<hr>
<img src="https://media.geeksforgeeks.org/wp-content/uploads/20220721080308/array.png" height=170, width=600 >
<br>
<br>

<a href="https://pythontutor.com/python-debugger.html#mode=edit"><h3>Visualize problems here</h3></a>

In [ ]:
#Printing an array  Using built in functions
a=[1,2,3,4,5,6]
print(a,"\n====") #printing the whole array
print(*a,sep="\n") # printing array elements only

[1, 2, 3, 4, 5, 6] 
====
1
2
3
4
5
6


In [ ]:
a=[10,20,30,40,50,60] #its an array so all elements are same or homogenous(int or string or float etc)
for i in range(0,len(a),1):
    print(a[i])

10
20
30
40
50
60


In [ ]:
a=[10,20,30,40,50,60] #Printing an array using for loop
print("=====RIGHT WAY =====")

def print_arr(data):

    for i in range(0,len(data),1):
        print(data[i])

print_arr(a)
#=======================================================

print("\n========WRONG WAY ========")

def print_a(data):
    for i in range(0,len(data),1):
        return(data[i])

print(print_a(a),"\n\nThis method is wrong as the function will only retun the first element and stop rather traversing the whole array.\n as a result you only see the first element while you print the array ")

=====RIGHT WAY =====
10
20
30
40
50
60

========WRONG WAY ========
10 

This method is wrong as the function will only retun the first element and stop rather traversing the whole array.
 as a result you only see the first element while you print the array 


In [ ]:
a=[10,20,30,40,50,60] #Printing an array reverse using for loop

def reverse_print(data):

    for i in range(len(data)-1,-1,-1):
        print(data[i])

reverse_print(a)
#============================================
def using_while(data):
    i=len(data)-1
    print("\n======Using whiel Loop !====== \n")
    while i>=0:
        print(data[i])
        i-=1
using_while(a)


60
50
40
30
20
10

======Using whiel Loop !====== 

60
50
40
30
20
10


In [ ]:
# copy array
#Note: You cannot edit an array once it is declared !
arr=[10,20,30,40,50,60,70,80,90,100]

def copy_ar(data):
    new_arr=[None]*len(data)
    print("This is the new empty array with 'None' values you just created\nlenght same as original array\n======\n",new_arr)

    for i in range (0,len(data),1):
        new_arr[i]=data[i]
    print("====\n\nThis is the new array you just made a copy of\n====\n")
    return new_arr
print(copy_ar(arr))

This is the new empty array with 'None' values you just created
lenght same as original array
 [None, None, None, None, None, None, None, None, None, None]
====

This is the new array you just made a copy of
====

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]


In [ ]:
#Resizing an array.
#Step-1 make a new array with new size
#step 2- transfer old elements to new array
arr=[10,20,30,40,50,60,70,80,90,100]         #lenght=10 but indexrange [0-9]

def resize(old_array,new_size):
    new_arr=[None]*new_size
    if new_size<len(old_array):
        return "New array must be Longer in size !"
    print("This is the new array with the given size\n====\n",new_arr)

    for i in range(0,len(old_array)):
        new_arr[i]=old_array[i]

    print("\n\nThis is the new array with the resized elements\n==== ")
    return new_arr

print(resize(arr,15))

This is the new array with the given size
====
 [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]


This is the new array with the resized elements
==== 
[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, None, None, None, None, None]


In [ ]:
#reversing an array by creating a new array
#Out of the place operation
arr=[10,20,30,40,50,60,70,80,90,100]

def rev_arr(data):
    new_arr=[None]*len(data)
    print("This is new array with same lenght\n====\n",new_arr)
    j=0
    for i in range(len(data)-1,-1,-1):
        new_arr[j]=data[i]
        j+=1
    print("\nNew reversed array out of the place\n====")
    return new_arr


print(rev_arr(arr))

This is new array with same lenght
====
 [None, None, None, None, None, None, None, None, None, None]

New reversed array out of the place
====
[100, 90, 80, 70, 60, 50, 40, 30, 20, 10]


In [ ]:
#reversing an array by not creating a new array
#In place operation

arr=[10,20,30,40,50,60,70,80,90,100]

def in_place(data):
    i=0
    l=len(data)-1
    u=0

    if len(data)%2!=0:
        u=len(data)//2              #must use floor divide to divide the lenght using len()
    else:
        u=(len(data)//2)-1        #You cannot normally divide a lenght of a data using normal devide


    for j in range(l,u,-1):
        temp=data[i]
        data[i]=data[j]
        data[j]=temp
        i+=1
    return data


print(in_place(arr))

[100, 90, 80, 70, 60, 50, 40, 30, 20, 10]


In [ ]:
#Shifting an array left
arr=[10,20,30,40,50,60,70,80,90,100]

def shift_left(data):
    for i in range(1,len(data)):
        data[i-1]=data[i]
    data[len(data)-1]=None
    return data

print(shift_left(arr))

[20, 30, 40, 50, 60, 70, 80, 90, 100, None]


In [ ]:
#rotating array left or circular rotation
arr=[10,20,30,40,50,60,70,80,90,100]

def rotate_left(data):
    temp=data[0]
    for i in range (1,len(arr)):
        data[i-1]=data[i]
    data[len(data)-1]=temp
    return data

print(rotate_left(arr))

[20, 30, 40, 50, 60, 70, 80, 90, 100, 10]


In [ ]:
#Shifting an array right
arr=[10,20,30,40,50,60,70,80,90,100]

def shift_right(data):

    for i in range(len(data)-1,-1,-1):
        data[i]=data[i-1]
    data[0]=None
    return data

print(shift_right(arr))

[None, 10, 20, 30, 40, 50, 60, 70, 80, 90]


In [ ]:
#rotating array right or circular rotation
arr=[10,20,30,40,50,60,70,80,90,100]

def rotate_right(data):
    temp=data[len(data)-1]
    for i in range (len(data)-1,-1,-1):
        data[i]=data[i-1]
    data[0]=temp
    return data

print(rotate_right(arr))

[100, 10, 20, 30, 40, 50, 60, 70, 80, 90]


In [ ]:
#Inserting element into an array
arrr=[1,2,3,4,5,6,7,None,None,None]

def insrt_elem(arr,size,elem,index):

    if size==len(arr):
        print("Nospace left!")

    else:
        for i in range (size,index,-1):
            arr[i]=arr[i-1]   #shifting untill right index
        arr[index]=elem       #Inserting element
        return arr

print(insrt_elem(arrr,7,200,3))

[1, 2, 3, 200, 4, 5, 6, 7, None, None]


In [ ]:
#Removing an element from an array
arrr=[10,20,30,40,50,60,70,80,90,100]

def rmv(arr,index,size):
    for i in range(index+1,size):
        arr[i-1]=arr[i]
    arr[size-1]=None
    return arr
print(rmv(arrr,3,10))


[10, 20, 30, 50, 60, 70, 80, 90, 100, None]


In [ ]:
#creating an numpy array
import numpy as np
arr= np.array([10,20,30,40,50,60,70,80,90,100])
print(arr)
print(type(arr))

[ 10  20  30  40  50  60  70  80  90 100]
<class 'numpy.ndarray'>


In [ ]:
#printing an array till a certain size # you must run the previous cell to import array to memory or the code will not work
def new_array(a,size): #a=[10 20 30 40 50 60 70 80 90 100],size=6
  new=np.zeros(size,dtype=np.int64)
  print(new,"<-- this is the new empty array of the certain size that you gave!\n\n====ANS====")

  for i in range(0,size,1):  #0,1,2,3,4,5
    new[i]=a[i]
  return new

print(new_array(arr,6))

[0 0 0 0 0 0] <-- this is the new empty array of the certain size that you gave!

====ANS====
[10 20 30 40 50 60]



<center><h1><b>Week-2</h1></b></center>
<center><h1><b>Multi Dimensional Array</h1></b></center>
<hr>

![alt text](https://media.geeksforgeeks.org/wp-content/uploads/3D-array.jpg)


<a href="https://pythontutor.com/python-debugger.html#mode=edit"><h3>Visualize problems here</h3></a>

In [ ]:
import numpy as np

In [ ]:

#making an One dimensional array
a=np.zeros(3,dtype=np.int64)
print(a)

[0 0 0]


In [ ]:

#making an multi dimensional array
a=np.zeros((2,3),dtype=np.int64)
print(a)

[[0 0 0]
 [0 0 0]]


In [ ]:
#creating an array using the array function
m= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# creating a matrix!

def matrix(data1,data2):
    arr=np.zeros((data1,data2),dtype=int)
    for i in range(data1):
        for j in range(data2):
            print(f"Enter element of[{i}][{j}] indexes:")
            arr[i][j]=int(input())
    return arr
print(matrix(3,3))

Enter element of[0][0] indexes:
1
Enter element of[0][1] indexes:
2
Enter element of[0][2] indexes:
3
4
Enter element of[1][0] indexes:
Enter element of[1][1] indexes:
5
Enter element of[1][2] indexes:
6
Enter element of[2][0] indexes:
7
Enter element of[2][1] indexes:
8
Enter element of[2][2] indexes:
9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#iterations of Matrixes
rows=3
cols=3
a=np.zeros((rows,cols),dtype=np.int64)
for i in range(rows):
    for j in range(cols):
        a[i][j]=int(input(f"Oi values de [{i}][{j}]-->"))
print(a)

for i in range(0,rows): #row wise itteration
    for j in range(0,cols): #column wise itteration
        print(f"Eita matrix er row x columns er value[{i}] [{j}] or-->\n {a[i][j]} ")

Oi values de [0][0]-->1
Oi values de [0][1]-->2
Oi values de [0][2]-->3
Oi values de [1][0]-->4
Oi values de [1][1]-->5
Oi values de [1][2]-->6
Oi values de [2][0]-->7
Oi values de [2][1]-->8
Oi values de [2][2]-->9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Eita matrix er row x columns er value[0] [0] or-->
 1 
Eita matrix er row x columns er value[0] [1] or-->
 2 
Eita matrix er row x columns er value[0] [2] or-->
 3 
Eita matrix er row x columns er value[1] [0] or-->
 4 
Eita matrix er row x columns er value[1] [1] or-->
 5 
Eita matrix er row x columns er value[1] [2] or-->
 6 
Eita matrix er row x columns er value[2] [0] or-->
 7 
Eita matrix er row x columns er value[2] [1] or-->
 8 
Eita matrix er row x columns er value[2] [2] or-->
 9 


In [ ]:
#trace finding of a matrix #Done later in this Note book
a=np.array([[1,2,3],[4,5,6],[7,8,9],],dtype=np.int64)
print("====> this is your matrix <====\n",a)


====> this is your matrix <====
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# rotating rows to columns and columns to rows out of the place
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
def change_rotation(data):
    row,col=data.shape
    temp=np.zeros((row,col),dtype=int)
    if row!=col:
        return ("Not possible!")
    for i in range(row):
        for j in range(col):
            temp[j][i]=data[i][j]
    return temp
print(change_rotation(matrix))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])    # rotationg rows to columns and columns to rows in  place
def change_rotation_inplace(data):
    row,col=data.shape
    if row!=col:
        return ("Not possible!")
    for i in range(row):
        for j in range(col):
            if i<j:
                up_value=data[i][j]
                low_value=data[j][i]
                data[i][j]=low_value
                data[j][i]=up_value
    return data
print(change_rotation_inplace(matrix))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
#main trace of a matrix
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
def main_trace(data):
    row,col=data.shape
    if row!=col:
        return ("Not possible!")
    temp=0
    for i in range(row):
        for j in range(col):
            if i==j:
                temp+=data[i][j]

    return temp

print(main_trace(matrix))

15


In [ ]:
#Secondary trace of a matrix
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
def second_trace(data):
    row,col=data.shape
    if row!=col:
        return ("Not possible!")
    temp=0
    for i in range(row):
                temp+=data[i][row-1-i]
    return temp
print(second_trace(matrix))

15



<center><h1><b>Week-3</h1></b></center>
<center><h1><b>Linked List </h1></b></center>
<hr>
<img src="https://study.com/cimages/multimages/16/circularly_linked_lists.png",
 height=400, width=600>

<a href="https://pythontutor.com/python-debugger.html#mode=edit"><h3>Visualize problems here</h3></a>

My problems in linked list
1.   Inserting elements in linked list
2.   Reversing In place
3.   Rotate Right



In [ ]:
import numpy as np
arr=np.array([10,20,30,40,50,60,70])
print(arr)

[10 20 30 40 50 60 70]


In [ ]:
class Node:                           #creating the main class of the link list
    def __init__(self,elem,next=None):
        self.element=elem
        self.next=next


In [ ]:
#creating a linked list !
def create(arr):
    head=Node(arr[0],None)
    tail=head
    for i in range(1,len(arr)):        #can not use 0 as  starting index or it will print 10 twice
        temp=Node(arr[i],None)
        tail.next=temp
        tail=temp
    return head

In [ ]:
#itterating an linked list


def itr(head):
    temp=head
    while temp!=None:
        if temp.next!=None:
            print(temp.element,end="-->")
        else:
            print(temp.element)

        temp=temp.next



head=create(arr) #will create the list
itr(head)

10-->20-->30-->40-->50-->60-->70


In [ ]:
def count_a(data):
    counter=0
    cur=data
    while cur!=None:
        counter+=1
        cur=cur.next
    return counter
print(count_a(head))


7


In [ ]:
# printing elements at a certain index      #10 20 30 40 50 60 70

def at(data,indx):
    cur=data
    idx=0

    while cur!=None:
        if idx==indx:
            return cur.element
        else:
            idx+=1
            cur=cur.next
print(at(head,4))

50


In [ ]:
#retrevieng element from an index  [10 20 30 40 50 60 70]
#The above cell is the same code just here if the index dosent exist it returns a warning just.
def elem_at(obj,idx):
    cur=obj
    counter=0
    while cur!=None:
        if idx==counter:
            return cur.element
        else:
            counter+=1
            cur=cur.next

    if 0<=idx and idx>=counter:
        return "Invalid Index"

print(elem_at(head,5))
print(elem_at(head,20))


60
Invalid Index


In [ ]:
#same code just showing the diiference in printing what will print what
#retrevieng the object from an index  [10 20 30 40 50 60 70]
def obj_at(obj,idx):
    cur=obj
    counter=0

    while cur!=None:
        if idx==counter:
            return cur
        else:
            counter+=1
            cur=cur.next

    if 0<=idx and idx>=counter:
        return "Invalid Index"

print(obj_at(head,5))                  # sends back the object
print(obj_at(head,5).element)         # sends back the element of that obj
print(obj_at(head,5).next.element)    #prints the element of the next obj that i called initially.
print(obj_at(head,20))                #Prints Invalid as index 20 does not exsist
print(obj_at(head,0).next.next.next.next.next.next.element) #Just a crazy interpretetion of how can we print the next elements using oop

60
70
Invalid Index
70


In [ ]:
#Updating value of a specific index. [10 20 30 40 50 60 70]
print("The old linked list !\n")
itr(head)
print("\n")
#________________Code starts from here_________________________
def update_value(obj,idx,elem):
    count=0
    temp=obj
    status=False
    while temp!=None:
        if count==idx:
            temp.element=elem
            status=True
            break
        count+=1
        temp=temp.next
    if status==True:
        return "Value Updated !"
    else:
        return "Error ! "

print(update_value(head,6,4000))
print("The new linked list!\n")
itr(head)

The old linked list !

10-->20-->30-->40-->50-->60-->70


Value Updated !
The new linked list!

10-->20-->30-->40-->50-->60-->4000


In [ ]:
#Searching an element in the linked list (Linear search !)
def search(obj,elem):                                     #[10 20 30 40 50 60 4000]
    count=0
    temp=obj

    while temp!=None:
        if elem==temp.element:
            return f"The element is at index--> {count}"
        count+=1
        temp=temp.next
    return "Sorry the element is not in the linked list !"

print(search(head,4000)) #returning the elements index after the search
print(search(head,200))  #Prrinting the error statement as the value is not in the linked list

The element is at index--> 6
Sorry the element is not in the linked list !


In [ ]:
#Inserting an element into a linked list
#we need to use the previous count function
data=[1,2,3,4,5,6,7,8,9,10]
def insrt(obj,elem,idx):
    totalnodes=count_a(obj)

    if idx==0:
        temp=Node(elem,obj)
        obj=temp
        return obj
    elif idx!=0 and idx<totalnodes:
        temp=Node(elem,None)
        n=obj_at(obj,idx-1)
        nxt=n.next
        n.next=temp
        temp.next=nxt
        return obj


    elif idx==totalnodes:
        temp_obj=Node(elem,None)
        temp=obj_at(obj,idx-1)
        temp.next=temp_obj
    return obj

obj_main=create(data)
obj_main1=create(data)
obj_main2=create(data)
#itr(obj_main)
test1=insrt(obj_main,300,0)
test2=insrt(obj_main1,50000,10)
test3=insrt(obj_main2,500,1)
itr(test1)
print()
itr(test2)
print()
itr(test3)

300-->1-->2-->3-->4-->5-->6-->7-->8-->9-->10

1-->2-->3-->4-->5-->6-->7-->8-->9-->10-->50000

1-->500-->2-->3-->4-->5-->6-->7-->8-->9-->10


In [ ]:
#removing an element from a list
data=[100,200,300,400,500,600,700,800,900,1000]
obj2=create(data)
#_________Actual Code______________  O==obj

def rmv(o,idx):
    if idx==0:
        o=o.next
    elif 1<=idx<=count_a(o):
        tempobj=obj_at(o,idx-1)
        remove=tempobj.next
        tempobj.next=remove.next
    else:
        print("Invalid index !")
    return o


test=rmv(obj2,0)   # 1st index is removed from the linked list
itr(test)
print("\n______________________________________________")
test=rmv(obj2,7)   # 7 no obj is removed from the linked list
itr(test)
print("\n______________________________________________")
test=rmv(obj2,11)   # Invalid index check
itr(test)

200-->300-->400-->500-->600-->700-->800-->900-->1000

______________________________________________
100-->200-->300-->400-->500-->600-->700-->900-->1000

______________________________________________
Invalid index !
100-->200-->300-->400-->500-->600-->700-->900-->1000


In [ ]:
#Copying a list
data=["A","B","C","D","E"]
obj3=create(data) #creating a new linked list in the obj3 head
#__________________________________________________
def copy_m(data):       #data parameter will receive the obj---> obj3 only
    temp=data
    new_head=None
    new_tail=None

    while temp!=None:
        m=Node(temp.element,None)
        if new_head==None:
            new_head=m
            new_tail=new_head
        else:
            new_tail.next=m
            new_tail=new_tail.next
        temp=temp.next
    return new_head

test=copy_m(obj3)  #returns a new linked list
itr(test)

print("\n",obj3,test,sep="\n") #the two addresses are different so the values of the two linked list are same but the lists are in  different loacations

A-->B-->C-->D-->E




In [ ]:
#Reversing a list Out of place
data=["A","B","C","D","E"]
obj4=create(data) #creating a new linked list in the obj4 head
#__________________________________________________________________________
def rev(data):
    new_head=Node(data.element,None)
    temp=data.next
    while temp!=None:
        m=Node(temp.element,new_head)
        new_head=m
        temp=temp.next
    return new_head

test=rev(obj4)
itr(test)

E-->D-->C-->B-->A


In [ ]:
#reverse in place
#Reversing a list in place
data=["u","v","w","x","y","z"]
obj5=create(data) #creating a new linked list in the obj5 head
#__________________________________________________________________________
def rev_in(data):
    new_head=None
    temp=data
    while temp!=None:
        m=temp.next
        temp.next=new_head
        new_head=temp
        temp=m
    return new_head


test=rev_in(obj5)
itr(test)

z-->y-->x-->w-->v-->u


In [ ]:
#rotating left
data=["u","v","w","x","y","z"]
obj6=create(data) #creating a new linked list in the obj6 head
#__________________________________________________________________________
def rotate_left(data):
    new_head=data.next
    temp=new_head
    while temp.next!=None:
        temp=temp.next
    temp.next=data
    data.next=None
    data=new_head
    return data


test=rotate_left(obj6)
itr(test)

v-->w-->x-->y-->z-->u


In [ ]:
#rotating right
data1=["u","v","w","x","y","z"]
obj7=create(data1) #creating a new linked list in the obj7 head
#__________________________________________________________________________
def rotate_right(data):
    head=data
    temp=data
    while temp.next.next!=None:
        temp=temp.next

    new_head=temp.next
    temp.next=None
    new_head.next=head
    return new_head


test1=rotate_right(obj7)
itr(test1)

z-->u-->v-->w-->x-->y



<center><h1><b>Week-4</h1></b></center>
<center><h1><b> Dummy Headed Doubly Circular Linked List</h1></b></center>
<hr>

![alt text](https://media.geeksforgeeks.org/wp-content/uploads/Delete_first_node.png)


<a href="https://pythontutor.com/python-debugger.html#mode=edit"><h3>Visualize problems here</h3></a>

In [ ]:
import numpy as np
arr=np.array(['A','B','C','D','E','F','G','H','I','J'])
print(arr)

['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J']


In [ ]:
class D_node:
     def __init__(self,elem=None,next=None,previous=None):
        self.element=elem
        self.next=next
        self.prev=previous

In [ ]:
##creating the list
def create_list(data):
    dh=D_node(None,None,None)
    dh.next=dh
    dh.prev=dh
    tail=dh

    for i in range(len(data)):
        m=D_node(data[i],dh,tail)
        tail.next=m
        tail=tail.next
        dh.prev=tail
    return dh

test=create_list(arr)

In [ ]:
#itteration of the list
def d_itr(data):
    temp=data.next
    while temp!=data:
        print(temp.element,end=" ")
        temp=temp.next
d_itr(test)

A B C D E F G H I J 

In [ ]:
#Locating a node by index
def N_at(data,idx):
    temp=data.next
    count=0
    while temp!=data:
        if count==idx:
            return temp
        count+=1
        temp=temp.next
    return "Invalid index"

print(N_at(test,5))   #this prints the obj location
print("\n",(N_at(test,0).element)) #this prints the element
print("\n",(N_at(test,0).next.element)) #this prints the next element
print("\n",(N_at(test,0).prev.element)) #this prints the previous element which is the doubly node and the element of that node is None


 A

 B

 None


In [ ]:
#Inserting a node in the linked list
data=["u","v","w","x","y","z"]
obj7=create_list(data) #creating a new linked list in the obj7 head
#______________________________________________________________________
def d_insrt(dh,elem,idx):
    node_to_insrt=D_node(elem,None,None)
    indexed_node=N_at(dh,idx)
    prev_node=indexed_node.prev

    node_to_insrt.next=indexed_node
    node_to_insrt.prev=prev_node
    prev_node.next=node_to_insrt
    indexed_node.prev=node_to_insrt


d_insrt(obj7,200,3) #inserted 200 at index 3 at the object list
d_itr(obj7)

u v w 200 x y z 

In [ ]:
#removal
#please rin the previous cell to work the code in this cell
#We will remove the 200 from the previous code
d_itr(obj7)
print() # Just to give a line gap
#_____________________________________________________________________
def d_rmv(data,idx):
    node_to_rmv=N_at(data,idx)
    prev=node_to_rmv.prev
    next=node_to_rmv.next

    prev.next=next
    next.prev=prev
    node_to_rmv.next=None
    node_to_rmv.prev=None

d_rmv(obj7,3)
d_itr(obj7) #No 200 in the final doubly linked list

u v w 200 x y z 
u v w x y z 


<center><h1><b>Week-5</h1></b></center>
<center><h1><b> STACK </h1></b></center>
<hr>

![alt text](https://edurev.gumlet.io/ApplicationImages/Temp/1611931_a6a559cc-f481-4c07-a483-c2c5461a2de6_lg.png?w=400&dpr=2.6)


<a href="https://pythontutor.com/python-debugger.html#mode=edit"><h3>Visualize problems here</h3></a>

In [ ]:
#stack
class Node:
    def __init__(self,element,next=None):
        self.elem=element
        self.next=next
class Stack:
    def __init__(self):
        self.top=None
    def push(self,elem):
        if self.top==None:
            self.top=Node(elem,None)
        else:
            obj=Node(elem,None)
            obj.next=self.top
            self.top=obj
    def peek(self):
        if self.top==None:
            return False
        return self.top.elem
    def pop(self):
        if self.top==None:
            return "Stack is Empty!"
        else:
            temp=self.top
            self.top=self.top.next
            temp.next=None
            return temp.elem

    def is_empty(self):
        if self.top== None:
            return True
        return False

test=Stack()
print(test.is_empty())
print(test.peek())
test.push(1)
print(test.peek())
test.push(2)
print(test.peek())
test.push(3)
print(test.peek())
test.push(4)
print(test.peek())
print(test.is_empty())
print(test.pop())
print(test.pop())
print(test.pop())
print(test.pop())
print(test.pop())

True
False
1
2
3
4
False
4
3
2
1
Stack is Empty!


In [ ]:
#reversing a stack
def rev(data):
    n=Stack()
    for i in data:
        n.push(i)
    new=""

    while n.is_empty()==False:
        new+=n.pop()
    return new

print(rev("I ! love Bracu"))

ucarB evol ! I


In [ ]:
#Prenthesis balance!
def balance(data):
    bag=Stack()
    open=["(","{","["]
    close=[")","}","]"]
    dic={")":"(","}":"{","]":"["}

    for i in range(len(data)):
        if data[i] in open:
            bag.push(data[i])
        elif data[i] in close:
            if bag.top==None:
                return False
            else:
                y=bag.pop()
                if dic[data[i]]!=y:
                    return False
    if bag.top==None:
        return True
    else:
        return False


print(balance("(a+b)"))
print(balance('1+2*[3*3+{4–5(6(7/8/9)+10)–11+(12*8)]+14'))
print(balance('([A+B]-C)/{D*E}+[2*[(2A+5){5B}]-{7C-9AB}]'))
print(balance("(){}["))

True
False
True
False


In [ ]:
def calculate(data):
    bag=Stack()
    op=["+","-","*","/"]
    for i in data:
        if i in op:
            v2=int(bag.pop())
            v1=int(bag.pop())
            temp=0
            if i=="+":
                temp=v2+v1
            elif i=="-":
                temp=v2-v1
            elif i=="*":
                temp=v2*v1
            else:
                temp=v2/v1
            bag.push(temp)

        else:
            bag.push(i)

        return bag.peek()



print(calculate("99+2/"))

9


In [ ]:
#Worst Case scenario Don't have to learn this unless you want to master DSA
#Also the code below is incomplete as it went over the head
def convert(data):
    open=["(","{","["]
    close=[")","}","]"]
    oprt=["+","-","*","/"]
    dic={"+":1,"-":1,"*":3,"/":3,"^":4}
    dic_close={")":"(","}":"{","]":"["}
    string=""
    bag=Stack()
    for i in data:
        if i in "ABCDEFGHIJKLMNOPQRSTUVWXYZ":
            string+=i
        elif i in open:
            bag.push(i)
        elif i in oprt:
            y=bag.peek()
            if y==False:
                bag.push(i)
            elif y in open:
                bag.push(i)
            elif dic[i] < dic[y] or dic[i]==dic[y]:
                string+=bag.pop()
                bag.push(i)
            elif dic[i]> dic[y]:
                bag.push(i)
        elif i in close:
            string+=bag.pop()





    return string
print(convert("A*(B*C+D*E)+F"))
print("To be continued Not complete ! Worst case scenario in CSE-220 !")

ABC*DE*+F
To be continued Not complete ! Wost case scenario in CSE-220 !



<center><h1><b>Week-6</h1></b></center>
<center><h1><b> Queue </h1></b></center>
<hr>

![alt text](https://media.geeksforgeeks.org/wp-content/cdn-uploads/20221213111946/fifo-property-in-Queue.png)


<a href="https://pythontutor.com/python-debugger.html#mode=edit"><h3>Visualize problems here</h3></a>

###***Singly Linked list Based Queue***

In [ ]:
class Node:
    def __init__(self,element,next=None):
        self.elem=element
        self.next=next

In [ ]:
#print the whole queue
def print_queue(data):
    temp=data
    while temp!=None:
        if temp.next!=None:
            print(temp.elem,end="-->")
        else:
            print(temp.elem)
        temp=temp.next

In [ ]:
class Queue:
    def __init__(self):
        self.front=None
        self.back=None
    def enqueue(self,data):
        if self.front==None:
            self.front=Node(data,None)
            self.back=self.front
        else:
            node=Node(data,None)
            self.back.next=node
            self.back=node

    def dequeue(self):
        if self. front==None:
            print("The queue is empty !")
        else:
            temp=self.front.elem
            self.front=self.front.next
            print(temp)
    def peek(self):
        if self.front==None:
            print( "The Queue is empty ! ")
        print(self.front.elem)
test=Queue()
test.enqueue(1)
test.enqueue(2)
test.enqueue(3)
test.enqueue(4)
test.enqueue(5)
test.enqueue(6)
test.enqueue(7)
test.enqueue(8)
test.enqueue(9)
test.enqueue(10)
print("="*50)
print_queue(test.front)
print("="*50)
test.dequeue()    #1 removed
test.dequeue()    #2 removed
test.dequeue()    #3 removed
test.peek()
print("="*50)
print_queue(test.front)
print("="*50)

1-->2-->3-->4-->5-->6-->7-->8-->9-->10
1
2
3
4
4-->5-->6-->7-->8-->9-->10


###***Array Based Queue***

In [ ]:
class Arrayqueue:
    def __init__(self):
        self.queue=[None]*10
        self.front=0
        self.back=0
        self.size=0
    def enqueue(self,elem):
        if self.size==len(self.queue):
            print("The queue is full please Dequeue!")
        else:
            self.queue[self.back]=elem
            self.back=(self.back+1)% len(self.queue)
            self.size+=1
    def dequeue(self):
        if self.size==0:
            print("The Queue is Empty !")
        else:
            self.size-=1
            temp=self.queue[self.front]
            self.queue[self.front]=None
            self.front=(self.front+1)%len(self.queue)
            print(temp)
    def peek(self):
        if self.size==0:
            print("The queue is empty !")
        print(self.queue[self.front])


tst=Arrayqueue()
tst.enqueue(10)
tst.enqueue(20)
tst.enqueue(30)
tst.enqueue(40)
tst.enqueue(50)
tst.enqueue(60)
tst.enqueue(70)
tst.enqueue(80)
tst.enqueue(90)
tst.enqueue(100)
print("Printing the whole queue-->",tst.queue,"\n")
print("="*10,'Dequeueing 3 elements',"="*10 )
tst.dequeue()
tst.dequeue()
tst.dequeue()      #dequeues 10,20,30 and replaces that spot with None
print("="*45)
print("\nPrinting the whole queue-->",tst.queue)
print("\nThis is the queue element ")
tst.peek()        #giving the first element of the queue as a output that is 40 now !

Printing the whole queue--> [10, 20, 30, 40, 50, 60, 70, 80, 90, 100] 

========== Dequeueing 3 elements ==========
10
20
30

Printing the whole queue--> [None, None, None, 40, 50, 60, 70, 80, 90, 100]

This is the queue element 
40


In [ ]:
#Recursion
# Do Your self

In [ ]:
#Hashing
#Do your self


<center><h1><b>Week-9</h1></b></center>
<center><h1><b> Tree </h1></b></center>
<hr>

![alt text](https://cdn1.byjus.com/wp-content/uploads/2022/01/tree.png)


<a href="https://pythontutor.com/python-debugger.html#mode=edit"><h3>Visualize problems here</h3></a>

In [ ]:
#Tree

In [ ]:
#Basic tree
class Node:
    def __init__(self,elem):
        self.elem=elem
        self.child=[]
root=Node(1)
root.child+=[Node(2),Node(3),Node(4)] #added 3 childreans to root node
print(root.child)
print("="*50)
root.child[0].child+=[Node(5),Node(6)]

print(root.child[0].child) #This prints the two childs of root 0 indexes.
print(root.child[0].child[0].elem) #this prints 5 as the elem of that tree node

[<__main__.Node object at 0x7eb32828ba60>, <__main__.Node object at 0x7eb32828b5b0>, <__main__.Node object at 0x7eb32828ace0>]
[<__main__.Node object at 0x7eb32828a3e0>, <__main__.Node object at 0x7eb32828a920>]
5


### ***Binary Tree From Array***

In [ ]:
class Node:
    def __init__(self,elem):
        self.elem=elem
        self.right=None
        self.left=None

In [ ]:
#Inorder traversal
def print_tree(root):
    if root!=None:
        print_tree(root.left)
        print(root.elem,end=" ")
        print_tree(root.right)

### ***Binary tree From an array !***

In [ ]:
def tree_maker(arr,i,n):
    root=None
    if i<n:
        if arr[i]!=None:
            root=Node(arr[i])
            root.left=tree_maker(arr,2*i,n)
            root.right=tree_maker(arr,2*i+1,n)
    return root

In [ ]:
#here total number of nodes are= 11
array=[None,"A","B","C","D","E","F","G","H",None,None,None,"I","J",None,"K"]
root=tree_maker(array,1,len(array))
print_tree(root)

H D B E A I F J C G K 

### ***Array From A Binary Tree***

In [ ]:
#Root height is 3 so total lenght is (3+1)**2= 16
arr_s=[None]*16
def array_maker(root,i):
    if root==None:
        return None
    else:
        arr_s[i]=root.elem
        array_maker(root.left,2*i)
        array_maker(root.right,2*i+1)
array_maker(root,1)
print(arr_s)


[None, 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', None, None, None, 'I', 'J', None, 'K']


In [ ]:
#total Number of nodes
def nodes_count(data):
    if data is None:
        return 0
    return 1+ nodes_count(data.left)+ nodes_count(data.right)

print(nodes_count(root))

11
